### ISSUE TITLE
Getting Hera-Monitoring working on AWS

### ISSUE THREAD

**Issue by ChrisJackson** [Nuance-Mobility/Hera-Monitoring#1]
Hi guys,

I like you're monitoring stack, basically perfect for what I'm wanting to do.  I've managed to get up and running using docker-machine, virtualbox and docker-compose.  In the end, I want to run the monitoring in AWS.  Doing the `docker-machine create --driver amazonec2 ........` no problems.  Running the 2 docker-compose commands, all works fine.  Doing a `docker ps` I can see the containers there when both commands are finished.  Wait 5 secs do another `docker ps` and the heramonitoring_monitorproxy_1, heramonitoring_sensuclient_1, heramonitoring_sensu_1, heramonitoring_graphite_1 and heramonitoring_logstash_1 containers disappear (shutdown).

1) Have you guys successfully run this solution on AWS?
2) Is there any gotchas, you can share.
3) looking at `docker logs heramonitoring_monitorproxy_1` it appears nginx exits unexpectedly.  When using docker-machine locally, vagrant appears to be mapping my local directories, but AWS does not.
So, from docker-compose.yml it appears maybe to be the issue.
volumes:
- ./nginx/config:/config
- ./nginx/html:/usr/share/nginx/html
- ./nginx/ssl:/etc/nginx/ssl

But, heramonitoring_grafana_1 doesn't appear to have this problem with its volume mappings.

Any advice, would be very much welcomed.

**Comment by ChrisJackson** [comment]
FYI -- worked it out.

The issue is that AWS does not have the container configuration files mapped the way Vagrant/Virtualbox does.  So, solution was to create a directory on host server via `docker-machine ssh` called 'run'.  

Edit the docker-compose.yml file and update all instances of "./" with "/home/ubuntu/run/"

volumes:
- /home/ubuntu/run/nginx/config:/config
- /home/ubuntu/run/nginx/html:/usr/share/nginx/html
- /home/ubuntu/run/nginx/ssl:/etc/nginx/ssl

Then `rsync -e 'ssh -vi /Users/XXX/.docker/machine/machines/test-monitoring/id_rsa ' --exclude .git/ -avz /Users/XXX/Hera-Monitoring/run/ ubuntu@$(docker-machine ip test-monitoring):~/run`

You can still orchestrate locally from your PC with docker-compose commands; 
`docker-compose -p heramonitoring -f data-containers.yml up -d`
`docker-compose -p heramonitoring up -d`

BUT, if you change any of the file in the run directory, don't forget to run the "rsync" command each time you do.

Thanks.

**Comment by djsly** [comment]
Hi  Chris, glad you were able to find a solution to your issue. Unfortunately, we haven't used Hera with a cloud provider so far. Your investigation shows that enhancement with regards to the config file could be performed to allow better / easier integration with different cloud provider.

We're happy that you like the stack!
